// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMKqdcFdbZHf_kyRUVfFbOcMvQ6CJHLoU',
    appId: '1:837485547481:web:10654dba428838467b53c8',
    messagingSenderId: '837485547481',
    projectId: 'flutter-chat-21860',
    authDomain: 'flutter-chat-21860.firebaseapp.com',
    storageBucket: 'flutter-chat-21860.appspot.com',
    measurementId: 'G-4MBVKE185S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVlvGCP8b11KW3QmvRfUCMP5uouUDxghc',
    appId: '1:837485547481:android:5d8234075147466d7b53c8',
    messagingSenderId: '837485547481',
    projectId: 'flutter-chat-21860',
    storageBucket: 'flutter-chat-21860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ_piADIDl-EF7Uq5Qbi1c85lAtQoQe64',
    appId: '1:837485547481:ios:b17e953ae04dfa297b53c8',
    messagingSenderId: '837485547481',
    projectId: 'flutter-chat-21860',
    storageBucket: 'flutter-chat-21860.appspot.com',
    iosClientId: '837485547481-8h0a36giu7bs9d000g8le3qesotgajdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ_piADIDl-EF7Uq5Qbi1c85lAtQoQe64',
    appId: '1:837485547481:ios:b17e953ae04dfa297b53c8',
    messagingSenderId: '837485547481',
    projectId: 'flutter-chat-21860',
    storageBucket: 'flutter-chat-21860.appspot.com',
    iosClientId: '837485547481-8h0a36giu7bs9d000g8le3qesotgajdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
